### ISSUE TITLE
GitHub Actionsでの自動テスト設定

### ISSUE THREAD

**Issue by becky3** [becky3/coin-hunter-adventure-pixel#24]
## 概要
CI/CDパイプラインを構築し、プルリクエスト時に自動的にテストを実行する環境を整備します。

## 親タスク
- #19 開発効率改善: 動作確認の自動化とデバッグ機能の強化

## 前提条件
- #20 自動テスト環境の構築が完了していること
- #22 主要クラスの単体テストが作成されていること

## 作業内容
- [ ] .github/workflows/test.yml の作成
- [ ] Node.js環境のセットアップ
- [ ] 依存関係のキャッシュ設定
- [ ] テスト実行とレポート生成
- [ ] カバレッジレポートの設定
- [ ] PR時の自動コメント機能

### 基本構成
```yaml
name: Test
on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run test:coverage
```

### 追加機能
- テスト結果のサマリー表示
- カバレッジの変化を PR コメントに表示
- 失敗時の詳細ログ出力
- パフォーマンステストの実行（将来的に）

## 受け入れ条件
- [ ] PRを作成時に自動的にテストが実行される
- [ ] テスト失敗時にマージがブロックされる
- [ ] カバレッジレポートが確認できる
- [ ] 実行時間が5分以内

## 優先度
高 - 品質保証の自動化に必須
